version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  django:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
  redis:
    image: redis:5.0.3-alpine
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
  celery:
    build: .
    command: celery -A flick worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: